apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: godemo
  name: godemo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: godemo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: godemo
    spec:
      containers:
      - image: meshboy/godeploy:1
        name: godemo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: lb-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: godeploy